# Monitoring Agent - Real-time Pipeline Guardian
name: green-ci-sentinel
version: 1.0.0
description: Real-time monitoring and alerting for pipeline sustainability

triggers:
  - pipeline_running:
      every: 60  # Check every 60 seconds
  - pipeline_failed
  - resource_alert

permissions:
  - read_api
  - read_observability

actions:
  - name: monitor_active_pipelines
    run: node /opt/green-ci/scripts/monitor-pipelines.js
    
  - name: detect_anomalies
    run: node /opt/green-ci/scripts/detect-anomalies.js
    condition: metrics.deviation > 2.0  # 2 standard deviations
    
  - name: emergency_response
    condition: metrics.carbon_spike > 0.5  # 0.5kg CO2 spike
    run: node /opt/green-ci/scripts/emergency-responder.js
    priority: high